version: "3.8"

networks:
  frontend:
    driver: ${DOCKER_NETWORKS_DRIVER}
  backend:
    driver: ${DOCKER_NETWORKS_DRIVER}

volumes:
  postgres:
    driver: ${DOCKER_VOLUMES_DRIVER}
  redis:
    driver: ${DOCKER_VOLUMES_DRIVER}

services:
  core:
    build:
      context: docker/image
      args:
        - USER_CONTAINER=${DOCKER_USER}
        - PUID=${DOCKER_PUID}
        - PGID=${DOCKER_PGID}
    restart: unless-stopped
    depends_on:
      - db
      - redis
    volumes:
      # laravel comes up with public dir inside workdir, so we will mount only /var/www
      - ./:/var/www
    ports:
      - ${DOCKER_PORT}:80
    networks:
      - frontend
      - backend
  db:
    image: mariadb/mariadb:10.6.4
    volumes:
      -- ${DOCKER_DATA_PATH_HOST}/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER:  ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
    networks:
      - backend
  redis:
    image: redis/redis:6.2.5-alpine3.14
    restart: unless-stopped
    volumes:
      - ${DOCKER_DATA_PATH_HOST}/redis:/data
    networks:
      - backend
