version: '3.7'

volumes:
    logs:
        driver: local
    monggodb:
        driver: local

services:
    slim:
        image: php:8.0.10-fpm-alpine3.13
        working_dir: /var/www
        environment:
            docker: "true"
        volumes:
            - .:/var/www
            - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
            - logs:/var/www/logs
        networks: 
            - punggawa
    nginx:
        image: nginx:1.20.1-alpine
        ports: 
            - "8080:80"
        volumes: 
            - .:/var/www
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks: 
            - punggawa
        depends_on: 
            - slim
    monggodb:
        image: mongo:5.0.2-focal
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin
        volumes:
            - 'monggodb:/data/db'
        networks:
            - punggawa
        ports:
        - "27019:27017"

networks:
    punggawa:
        driver: bridge
        
